--1. LIST DETAILS OF ALL EMPLOYEES BY EMPLOYEE NUMBER, LAST NAME, FIRST NAME, SEX, AND SALARY
--BY SELECTING INFO FROM EMPLOYEE TABLE AND DOING INNER JOIN ON SALARY TABLE BY EMP_NO
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, EMPLOYEES.SEX, SALARY.SALARY
FROM EMPLOYEES
INNER JOIN SALARY ON 
EMPLOYEES.EMP_NO = SALARY.EMP_NO;

--2. LIST FIRST NAME AND LAST NAME AND HIRE DATE FOR EMPLOYEES HIRED ON 1986.
--REFEERENCED https://www.sqltutorial.org FOR BETWEEN FUNCTION BY DATE FOR SQL
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '1986-01-01' AND '1986-12-31'

--3. LIST MANAGER OF EACH DEPARTMENT WITH THE FOLLOWING INFORMATION: DEPT_NO, DEPT_NAME, MANAGER EMP NO, LAST NAME, FIRST NAME
--FIRST CREATE A VIEW TO PUT TOGETHER THE DEPT NO AND NAME AND MANAGER
CREATE VIEW MANAGER_WITH_DEPT_NAME AS
SELECT DEPARTMENT.DEPT_NO, DEPARTMENT.DEPT_NAME, DEPT_MANAGER.EMP_NO
FROM DEPARTMENT
INNER JOIN DEPT_MANAGER ON 
DEPARTMENT.DEPT_NO = DEPT_MANAGER.DEPT_NO;

--SELECT ALL FROM VIEW TO MAKE SURE DEPT NO, DEPT NAME AND EMP NO ARE THERE
SELECT * FROM MANAGER_WITH_DEPT_NAME

--THEN FROM THE CREATED VIEW ADD THE LAST NAME AND FIRST NAME FROM THE EMPLOYEE TABLE AND JOIN TOGETHER FROM THE EMP_NO
SELECT MANAGER_WITH_DEPT_NAME.DEPT_NO, MANAGER_WITH_DEPT_NAME.DEPT_NAME, MANAGER_WITH_DEPT_NAME.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME
FROM EMPLOYEES
INNER JOIN MANAGER_WITH_DEPT_NAME ON
EMPLOYEES.EMP_NO = MANAGER_WITH_DEPT_NAME.EMP_NO;

--4. LIST THE DEPARTMENT OF EACH EMPLOYEE WITH EMPLOYEE NUM, LAST NAME, FIRST NAME, DEPT NAME.
--LIKE EXAMPLE ABOVE CREATE A VIEW TO LOOK AT THE EMPLOYEES WITH THE EMP_NO, AND THGE DEPT_NAME, AND NUMBER
CREATE VIEW EMPLOYEE_WITH_DEPARTMENT_NAMES AS
SELECT DEPT_EMP.EMP_NO, DEPT_EMP.DEPT_NO, DEPARTMENT.DEPT_NAME
FROM DEPT_EMP
INNER JOIN DEPARTMENT ON
DEPT_EMP.DEPT_NO = DEPARTMENT.DEPT_NO;

--SELECT ALL FROM VIEW TO MAKE SURE EACH EMPLOYEE HAS A DEPT NO AND DEPT NAME
SELECT * FROM EMPLOYEE_WITH_DEPARTMENT_NAMES

--ADD NAMES TO VIEW TO CREATE ALL DATA NEEDED
SELECT EMPLOYEE_WITH_DEPARTMENT_NAMES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, EMPLOYEE_WITH_DEPARTMENT_NAMES.DEPT_NAME
FROM EMPLOYEES
INNER JOIN EMPLOYEE_WITH_DEPARTMENT_NAMES ON
EMPLOYEES.EMP_NO = EMPLOYEE_WITH_DEPARTMENT_NAMES.EMP_NO;

--5. LIST FIRST NAME, LAST NAME, AND SEX FOR EMPLOYEES WHOSE FIRST NAME IS HURCULES AND LAST NAME BEGINS WITH B.
--REFERENCE FOR FINDING NAMES: https://www.geeksforgeeks.org/sql-query-to-find-the-name-of-a-person-whose-name-starts-with-specific-letter/
--SELECT ALL OF THE NAMES, AND SEX FOR ALL EMPLOYEES THEN FIND WHERE PERSONS FIRST NAME IS HURCULES AND THEN B% TO FIND ALL STARTING WITH B.
SELECT FIRST_NAME, LAST_NAME, SEX 
FROM EMPLOYEES
WHERE (FIRST_NAME LIKE 'Hercules') AND (LAST_NAME LIKE 'B%')

--6. LIST ALL EMPLOYEES IN THE SALES DEPARTMENT, INCLUDING THE EMP_NO, LAST & FIRST NAME, AND DEPARTMENT NAME.
--USE CREATE VIEW FOR ALL EMPLOYEES FROM PREVIOUS PART NUMBER 4, ADDED B AT AND FOR THIS TASK 
CREATE VIEW EMPLOYEE_WITH_DEPARTMENT_NAMES_B AS
SELECT DEPT_EMP.EMP_NO, DEPT_EMP.DEPT_NO, DEPARTMENT.DEPT_NAME
FROM DEPT_EMP
INNER JOIN DEPARTMENT ON
DEPT_EMP.DEPT_NO = DEPARTMENT.DEPT_NO;

--SELECT ALL FROM VIEW TO MAKE SURE EACH EMPLOYEE HAS A DEPT NO AND DEPT NAME
SELECT * FROM EMPLOYEE_WITH_DEPARTMENT_NAMES_B

--ADD NAMES TO VIEW TO CREATE ALL DATA NEEDED, THEN ADD WHERE DEPARTMENT NAME IS SALES
SELECT EMPLOYEE_WITH_DEPARTMENT_NAMES_B.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, EMPLOYEE_WITH_DEPARTMENT_NAMES_B.DEPT_NAME
FROM EMPLOYEES
INNER JOIN EMPLOYEE_WITH_DEPARTMENT_NAMES_B ON
EMPLOYEES.EMP_NO = EMPLOYEE_WITH_DEPARTMENT_NAMES_B.EMP_NO
WHERE (DEPT_NAME = 'Sales')

--7. LIST ALL EMPLOYEES IN THE SALES AND DELEVOPMENT DEPARTMENTS INCLUDE THE EMP_NO, LAST & FIRST NAME, AND DEPT NAME.
--SAME START AS NUMBER 6 JUST ADDING DEVELOPMENT TO WHERE 
CREATE VIEW EMPLOYEE_WITH_DEPARTMENT_NAMES_C AS
SELECT DEPT_EMP.EMP_NO, DEPT_EMP.DEPT_NO, DEPARTMENT.DEPT_NAME
FROM DEPT_EMP
INNER JOIN DEPARTMENT ON
DEPT_EMP.DEPT_NO = DEPARTMENT.DEPT_NO;

--SELECT ALL FROM VIEW TO MAKE SURE EACH EMPLOYEE HAS A DEPT NO AND DEPT NAME
SELECT * FROM EMPLOYEE_WITH_DEPARTMENT_NAMES_C

--ADD NAMES TO VIEW TO CREATE ALL DATA NEEDED, THEN ADD WHERE DEPARTMENT NAME IS SALES OR DEVELOPMENT
SELECT EMPLOYEE_WITH_DEPARTMENT_NAMES_C.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, EMPLOYEE_WITH_DEPARTMENT_NAMES_C.DEPT_NAME
FROM EMPLOYEES
INNER JOIN EMPLOYEE_WITH_DEPARTMENT_NAMES_C ON
EMPLOYEES.EMP_NO = EMPLOYEE_WITH_DEPARTMENT_NAMES_C.EMP_NO
WHERE (DEPT_NAME = 'Sales') OR (DEPT_NAME = 'Development')

--8. IN DESC ORDER LIST THE FREQUENCY COUNT OF EMPLOYEES LAST NAMES. 
-- SELECT ALL LAST NAMES AND COUNT THEM, THEN GROUP BY LAST NAME AND THEN ORDER BY DESCENDING 
SELECT LAST_NAME, COUNT(LAST_NAME) 
FROM EMPLOYEES
GROUP BY LAST_NAME 
ORDER BY COUNT(LAST_NAME) DESC;

